# Generated by Django 4.2 on 2023-04-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='textplace',
        ),
    ]
