# Generated by Django 4.2 on 2023-04-05 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 10, 51, 42, 949427)),
        ),
    ]
